### PR TITLE
Update dependencies.rosinstall

### PR DESCRIPTION
**Pull request by mosfet80**
update dependencies

### CODE REVIEW

**Comment by marip8** [comment]
Closing and re-opening to trigger CI

**Review by marip8 — APPROVED** [review]

**Comment by marip8** [comment]
The previous version of RICB includes `gtest` which was not distributed via binary on 18.04, so moving to a later version of RICB breaks the bionic build. Is there a reason we need to actually need to advance RICB?

**Comment by mosfet80** [comment]
@merip8 I changed the update library to version 0.3.1 . this is the last version before the gtest library is removed.
I look forward to finding a later solution to switch to version 0.4

**Comment by mosfet80** [comment]
On windows ....ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ros_industrial_cmake_boilerplate: No definition of [iwyu] for OS [windows]

I think it is necessary to add the iwyu windows references into https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml

**Comment by marip8** [comment]
> I think it is necessary to add the iwyu windows references into https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml

Possibly, but I think IWYU also needs to be released on Chocolatey for Windows, which [doesn't appear to be the case currently](https://github.com/include-what-you-use/include-what-you-use/issues/946). For Windows builds for other projects (like [`boost_plugin_loader`](https://github.com/tesseract-robotics/boost_plugin_loader/blob/main/.github/workflows/windows_2019.yml) and [`tesseract`](https://github.com/tesseract-robotics/tesseract/blob/master/.github/workflows/windows.yml)), it seems like we circumvent this issue by not running `rosdep`. Maybe we could do that here as well in the short term

**Comment by mosfet80** [comment]
I added the missing library patch in rosdep https://github.com/mosfet80/rosdistro/tree/patch-2
Once the patch is approved, the code should compile without changes.

**Pull request closed without merging**
